- name: Apply flannel cni
  kubernetes.core.k8s:
    state: present
    src: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    kubeconfig: "~{{ ansible_user }}/.kube/config"
    wait: true

- name: flannel fix crashloop
  copy:
    dest: /run/flannel/subnet.env
    content: |
      FLANNEL_NETWORK=10.240.0.0/16
      FLANNEL_SUBNET=10.240.0.1/24
      FLANNEL_MTU=1450
      FLANNEL_IPMASQ=true
  notify:
  - Restart kubelet
