---
- name: Rulebook to print debug message based on webhook event
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
            host: 0.0.0.0
            port: 6000

  rules:
      - name: Launch playbook on start command
        condition: event.payload.product.fullname == "Proxmox VE"
        action:
            run_module:
                name: ansible.builtin.template
                module_args:
                    src: ./inventory.yml.j2
                    dest: inventory.yml\
                    vars:
                      info: {{ event }}
            run_playbook:
                name: "hypervisor-setup.yml"
                extra_vars:
                    info: {{ event }}
