---
- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - epel-release
      - python3-pip
    state: present
    enablerepo:
      - crb

- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name:
      - kitty-terminfo
    state: present
    # need to set release ver as kitty terminfo is too new
    releasever: 10.1
    disablerepo:
      - docker-ce-stable
      # doesnt like the release ver


- name: Add Docker CE repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Verify Docker CE repository file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo

- name: Add Kubernetes repository
  ansible.builtin.template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name:
      - containerd.io
      - kubectl
      - kubelet
      - kubeadm
      - helm
    state: present
    disable_excludes: kubernetes

- name: Install pre-requisites
  pip:
    name:
      - pyyaml
      - kubernetes
