- name: Redhat specific install steps
  hosts: all
  become: yes
  vars:
    k8_version: v1.34
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name:
          - dnf-plugins-core
        state: present

    - name: Add Docker CE repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
    

    - name: Verify Docker CE repository file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/docker-ce.repo
    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name:
          - containerd.io
        state: present
    - name: Generate containerd config
      ansible.builtin.command:
        cmd: containerd config default
      
      register: containerd_config
    - name: Write config
      ansible.builtin.copy:
        content: containerd_config.stdout
        dest: /etc/containerd/config.toml
    
    - name: Configure Kubernetes prerequisites
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf


# install k8 repo with template file changing to  a module
    